version: '3.7'

services:
  api:
    build: 
      context: .
    command: python main.py
    volumes:
      - .:/app
      - 'C:\Program Files\Google\Chrome\Application\chrome.exe:/host-chrome'
      - /app/node_modules
    env_file:
      - ./.env    
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL_REMOTE}
    depends_on:
      - mongo

volumes:
  
  mongo-data:
    driver: local